#---
# Excerpted from "Metaprogramming Ruby: Program Like the Ruby Pros",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/ppmetr for more book information.
#---
#--
# DO NOT EDIT
# This file is auto-generated by build scripts.
# See:  rake update_version
#++

module Gem

  ##
  # The version of RubyGems you are using

  RubyGemsVersion = '1.3.3'

  ##
  # The version of RubyGems you are using (duplicated for familiarity)

  VERSION = RubyGemsVersion

end
